<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./public/assets/models/Stem2WebsiteModel-v2.glb -t -T
Cleaned up and ported to svelte 5 afterwards.
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group, Material, MeshBasicMaterial, MeshStandardMaterial } from "three";
  import { T } from "@threlte/core";
  import { type ThrelteGltf, useGltf } from "@threlte/extras";
  import { SheetObject } from "@threlte/theatre";

  export const ref = new Group();

  type Model = {
    nodes: {
      // Throttles
      Throttle_L: THREE.Mesh;
      Throttle_R: THREE.Mesh;
      Throttle_Main: THREE.Mesh;

      // Left Panels
      Solar_Panel_Front002_1: THREE.Mesh;
      Solar_Panel_Front002_2: THREE.Mesh;
      Solar_Panel_Front002_3: THREE.Mesh;

      // Right Panels
      Solar_Panel_Front003_1: THREE.Mesh;
      Solar_Panel_Front003_2: THREE.Mesh;
      Solar_Panel_Front003_3: THREE.Mesh;

      // Nose Meshes
      Nose_1: THREE.Mesh;
      Nose_2: THREE.Mesh;

      // Body Meshes
      Body_Back: THREE.Mesh;
      Body_Middle: THREE.Mesh;
      Body_Front: THREE.Mesh;

      // Centrifuge
      Centrifuge001: THREE.Mesh;

      // Poles
      Pole_1: THREE.Mesh;
      Pole_2: THREE.Mesh;
      Pole_3: THREE.Mesh;
    };
    materials: {
      ["Steel - Satin"]: THREE.MeshStandardMaterial;
      ["Dark Steel"]: THREE.MeshStandardMaterial;
      ["Titanium -  Pure"]: THREE.MeshStandardMaterial;
      ["Solar Panel"]: THREE.MeshStandardMaterial;
    };
  };

  const version = "5";
  const gltf = useGltf<Model>(`/assets/models/HeroModel-v${version}.glb`, {
    useDraco: "https://www.gstatic.com/draco/v1/decoders/",
  });

  interface Props {
    // ts-expect-error Sync is Any
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Sync: any;
  }

  let { Sync, ...props }: Props = $props();
  let clonedSteel: Material;
  let clonedDarkSteel: Material;
  let clonedTitanium: Material;
  let clonedSolarPanel: Material;

  /* Copy Steel Material */
  function getSteelMaterial(gltf: ThrelteGltf<Model>): Material {
    if (!clonedSteel) clonedSteel = gltf.materials["Steel - Satin"].clone();
    return clonedSteel;
  }

  /* Copy Dark Steel Material */
  function getDarkSteelMaterial(gltf: ThrelteGltf<Model>): Material {
    if (!clonedDarkSteel)
      clonedDarkSteel = gltf.materials["Dark Steel"].clone();
    return clonedDarkSteel;
  }

  /* Copy Titanium Material */
  function getTitaniumMaterial(gltf: ThrelteGltf<Model>): Material {
    if (!clonedTitanium)
      clonedTitanium = gltf.materials["Titanium -  Pure"].clone();
    return clonedTitanium;
  }

  function getGlassMaterial() {
    return new MeshStandardMaterial({ color: "lightyellow" });
  }

  /* Copy & Remove Solar Panels from Tone Mapping so they are Not a Beacon. */
  function getSolarPanelMaterial(gltf: ThrelteGltf<Model>): Material {
    if (!clonedSolarPanel) {
      clonedSolarPanel = gltf.materials["Solar Panel"].clone();
      clonedSolarPanel.toneMapped = false;
    }
    return clonedSolarPanel;
  }
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf then gltf}
    <!-- Throttles -->
    <SheetObject key="Parts / Throttles / Throttle L" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_L.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[-2.01, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        >
          <Sync material.opacity material.transparent />
        </T.Mesh>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Throttles / Throttle R" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_R.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[0.62, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Throttles / Throttle Main" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_Main.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[-0.81, 0.76, 28.73]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.31, 0.5, 1.31]}
        />
      </Transform>
    </SheetObject>

    <!-- Main Body -->
    <SheetObject key="Parts / Body / Nose" let:Transform>
      <Transform>
        <T.Group
          position={[-0.87, -0.29, -21.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <T.Mesh
            geometry={gltf.nodes.Nose_1.geometry}
            material={getSteelMaterial(gltf)}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <T.Mesh
            geometry={gltf.nodes.Nose_2.geometry}
            material={getGlassMaterial()}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Body / Body Front" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Front.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.87, -0.29, -21.27]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          recieveShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Body / Body Middle" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Middle.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          recieveShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Body / Body Back" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Back.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          recieveShadow
        />
      </Transform>
    </SheetObject>

    <!-- Centrifuge + Centrifuge Poles -->
    <SheetObject key="Parts / Centrifuge / Centrifuge 1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Centrifuge 2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, -Math.PI / 3, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Centrifuge 3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Centrifuge 4" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Centrifuge 5" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Centrifuge 6" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={getSteelMaterial(gltf)}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, Math.PI / 3, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Poles / Pole 1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_1.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[3.02, -0.57, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Poles / Pole 2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_2.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[-2.8, -3.91, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / Centrifuge / Poles / Pole 3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_3.geometry}
          material={getDarkSteelMaterial(gltf)}
          position={[-2.8, 3.27, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
          castShadow
        />
      </Transform>
    </SheetObject>

    <!-- Solar Panels -->
    <SheetObject key="Parts / SolarPanels / Solar Panel 1" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, 6.63]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={getTitaniumMaterial(gltf)}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / SolarPanels / Solar Panel 2" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, 6.63]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={getTitaniumMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / SolarPanels / Solar Panel 3" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -8.2]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={getTitaniumMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / SolarPanels / Solar Panel 4" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -4.6]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={getTitaniumMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / SolarPanels / Solar Panel 5" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, -8.2]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={getTitaniumMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Parts / SolarPanels / Solar Panel 6" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, -4.6]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={getTitaniumMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={getDarkSteelMaterial(gltf)}
          />
        </T.Group>
      </Transform>
    </SheetObject>
  {/await}

  {@html ref}
</T>
