<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./public/assets/models/Stem2WebsiteModel-v2.glb -t -T
Cleaned up and ported to svelte 5 afterwards.
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group, Material } from "three";
  import { T } from "@threlte/core";
  import { FakeGlowMaterial, type ThrelteGltf, useGltf } from "@threlte/extras";
  import type { Snippet } from "svelte";
  import { SheetObject } from "@threlte/theatre";
  import type { ISheetObject } from "@theatre/core";
  import type modelProps from "../../types/modelProps.ts";

  export const ref = new Group();

  type Model = {
    nodes: {
      // Throttles
      Throttle_L: THREE.Mesh;
      Throttle_R: THREE.Mesh;
      Throttle_Main: THREE.Mesh;

      // Left Panels
      Solar_Panel_Front002_1: THREE.Mesh;
      Solar_Panel_Front002_2: THREE.Mesh;
      Solar_Panel_Front002_3: THREE.Mesh;

      // Right Panels
      Solar_Panel_Front003_1: THREE.Mesh;
      Solar_Panel_Front003_2: THREE.Mesh;
      Solar_Panel_Front003_3: THREE.Mesh;

      // Nose Meshes
      Nose_1: THREE.Mesh;
      Nose_2: THREE.Mesh;

      // Body Meshes
      Body_Back: THREE.Mesh;
      Body_Middle: THREE.Mesh;
      Body_Front: THREE.Mesh;

      // Centrifuge
      Centrifuge001: THREE.Mesh;

      // Poles
      Pole_1: THREE.Mesh;
      Pole_2: THREE.Mesh;
      Pole_3: THREE.Mesh;
    };
    materials: {
      ["Steel - Satin"]: THREE.MeshStandardMaterial;
      ["Dark Steel"]: THREE.MeshStandardMaterial;
      ["Titanium -  Pure"]: THREE.MeshStandardMaterial;
      ["Solar Panel"]: THREE.MeshStandardMaterial;
    };
  };

  const version = "5";
  const gltf = useGltf<Model>(`/assets/models/HeroModel-v${version}.glb`, {
    useDraco: "https://www.gstatic.com/draco/v1/decoders/",
  });

  interface Props {
    fallback: Snippet;
    onError: Snippet<[Error]>;
    // ts-expect-error Sync is Any
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Sync: any;
    values: ISheetObject<typeof modelProps>["value"];
  }

  let { fallback, onError, Sync, values, ...props }: Props = $props();

  /* Remove Solar Panels from Tone Mapping so they are Not a Beacon. */
  function getSolarPanelMaterial(gltf: ThrelteGltf<Model>): Material {
    gltf.materials["Solar Panel"].toneMapped = false;
    return gltf.materials["Solar Panel"];
  }
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback()}
  {:then gltf}
    <!-- Throttles -->
    <SheetObject key="Model / Throttles / throttle-l" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_L.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.01, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        >
          <Sync material.opacity material.transparent />
        </T.Mesh>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Throttles / throttle-r" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_R.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[0.62, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Throttles / throttle-main" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_Main.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-0.81, 0.76, 28.73]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.31, 0.5, 1.31]}
        />
      </Transform>
    </SheetObject>

    <!-- Main Body -->
    <SheetObject key="Model / Body / nose" let:Transform>
      <Transform>
        <T.Group
          position={[-0.87, -0.29, -21.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <T.Mesh
            geometry={gltf.nodes.Nose_1.geometry}
            material={gltf.materials["Steel - Satin"]}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <!-- Use a special emissive "glass" material, + Normal Material. -->
          <T.Mesh geometry={gltf.nodes.Nose_2.geometry}>
            <T.MeshBasicMaterial color="lightyellow">
              <Sync opacity transparent />
            </T.MeshBasicMaterial>
          </T.Mesh>
          {#if values.opacity >= 1}
            <T.Mesh geometry={gltf.nodes.Nose_2.geometry}>
              <FakeGlowMaterial glowColor="lightyellow" />
            </T.Mesh>
          {/if}
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-front" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Front.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.87, -0.29, -21.27]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-middle" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Middle.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-back" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Back.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>

    <!-- Centrifuge + Centrifuge Poles -->
    <SheetObject key="Model / Centrifuge / centrifuge-1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, -Math.PI / 3, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-4" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-5" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-6" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, Math.PI / 3, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_1.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[3.02, -0.57, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_2.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.8, -3.91, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_3.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.8, 3.27, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>

    <!-- Solar Panels -->
    <SheetObject key="Model / SolarPanels / solar-panel-1" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, 5.63]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          >
            <Sync material.opacity material.transparent />
          </T.Mesh>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-2" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, 5.63]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-3" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -8.2]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front003_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-4" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -4.6]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-5" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, -8.2]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-6" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, -4.6]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_1.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_2.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel_Front002_3.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
  {:catch error}
    {@render onError(error)}
  {/await}

  {@html ref}
</T>
