<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./public/assets/models/Stem2WebsiteModel-v2.glb -t -T
Cleaned up and ported to svelte 5 afterwards.
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group, Material } from "three";
  import { T } from "@threlte/core";
  import { FakeGlowMaterial, type ThrelteGltf, useGltf } from "@threlte/extras";
  import type { Snippet } from "svelte";
  import { SheetObject } from "@threlte/theatre";

  export const ref = new Group();

  type Model = {
    nodes: {
      Throttle_R: THREE.Mesh;
      Throttle_L: THREE.Mesh;
      Body_Back: THREE.Mesh;
      Body_Front: THREE.Mesh;
      Pole_1: THREE.Mesh;
      Pole_2: THREE.Mesh;
      Pole_3: THREE.Mesh;
      Throttle_Main: THREE.Mesh;
      Solar_Panel005: THREE.Mesh;
      Solar_Panel005_1: THREE.Mesh;
      Solar_Panel005_2: THREE.Mesh;
      Body20002: THREE.Mesh;
      Body20002_1: THREE.Mesh;
      Body_Back001: THREE.Mesh;
      Solar_Panel004: THREE.Mesh;
      Solar_Panel004_1: THREE.Mesh;
      Solar_Panel004_2: THREE.Mesh;
      Centrifuge001: THREE.Mesh;
      Centrifuge002: THREE.Mesh;
      Centrifuge003: THREE.Mesh;
      Centrifuge004: THREE.Mesh;
      Centrifuge005: THREE.Mesh;
      Centrifuge006: THREE.Mesh;
      Solar_Panel007: THREE.Mesh;
      Solar_Panel007_1: THREE.Mesh;
      Solar_Panel007_2: THREE.Mesh;
    };
    materials: {
      ["Steel - Satin"]: THREE.MeshStandardMaterial;
      ["Dark Steel"]: THREE.MeshStandardMaterial;
      ["Titanium -  Pure"]: THREE.MeshStandardMaterial;
      ["Solar Panel.001"]: THREE.MeshStandardMaterial;
    };
  };

  const version = "2";
  const gltf = useGltf<Model>(
    `/assets/models/Stem2WebsiteModel-v${version}.glb`,
    {
      useDraco: "https://www.gstatic.com/draco/v1/decoders/",
    },
  );

  interface Props {
    fallback: Snippet;
    onError: Snippet<[Error]>;
  }

  let { fallback, onError, ...props }: Props = $props();

  /* Remove Solar Panels from Tone Mapping so they are Not a Beacon. */
  function getSolarPanelMaterial(gltf: ThrelteGltf<Model>): Material {
    gltf.materials["Solar Panel.001"].toneMapped = false;
    return gltf.materials["Solar Panel.001"];
  }
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback()}
  {:then gltf}
    <!-- Throttles -->
    <SheetObject key="Model / Throttles / throttle-l" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_L.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.01, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Throttles / throttle-r" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_R.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[0.62, -1.67, 28.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.75, 0.5, 0.75]}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Throttles / throttle-main" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Throttle_Main.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-0.81, 0.76, 28.73]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.31, 0.5, 1.31]}
        />
      </Transform>
    </SheetObject>

    <!-- Main Body -->
    <SheetObject key="Model / Body / nose" let:Transform>
      <Transform>
        <T.Group
          position={[-0.87, -0.29, -21.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <T.Mesh
            geometry={gltf.nodes.Body20002.geometry}
            material={gltf.materials["Steel - Satin"]}
          />
          <!-- Use a special emissive "glass" material, + Normal Material. -->
          <T.Mesh geometry={gltf.nodes.Body20002_1.geometry}>
            <T.MeshBasicMaterial color="lightyellow" />
          </T.Mesh>
          <T.Mesh geometry={gltf.nodes.Body20002_1.geometry}>
            <FakeGlowMaterial glowColor="lightyellow" />
          </T.Mesh>
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-front" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Front.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.87, -0.29, -21.27]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-middle" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Back.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Body / body-back" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Body_Back001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 11.59]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>

    <!-- Centrifuge + Centrifuge Poles -->
    <SheetObject key="Model / Centrifuge / centrifuge-1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge001.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge002.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, -Math.PI / 3, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge003.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-4" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge004.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-5" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge005.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / centrifuge-6" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Centrifuge006.geometry}
          material={gltf.materials["Steel - Satin"]}
          position={[-0.72, -0.32, 0.8]}
          rotation={[Math.PI / 2, Math.PI / 3, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-1" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_1.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[3.02, -0.57, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-2" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_2.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.8, -3.91, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>
    <SheetObject key="Model / Centrifuge / Poles / pole-3" let:Transform>
      <Transform>
        <T.Mesh
          geometry={gltf.nodes.Pole_3.geometry}
          material={gltf.materials["Dark Steel"]}
          position={[-2.8, 3.27, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        />
      </Transform>
    </SheetObject>

    <!-- Solar Panels -->
    <SheetObject key="Model / SolarPanels / solar-panel-1" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, 5.63]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-2" let:Transform>
      <Transform>
        <T.Group
          position={[-0.72, -0.19, 5.63]}
          rotation={[0, 0, 2.71]}
          scale={-1}
        >
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel005_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-3" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -8.2]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel004.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel004_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel004_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-4" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -4.6]} rotation={[Math.PI, 0, -2.71]}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-5" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -8.2]} rotation={[0, 0, 2.71]} scale={-1}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
    <SheetObject key="Model / SolarPanels / solar-panel-6" let:Transform>
      <Transform>
        <T.Group position={[-0.72, -0.19, -4.6]} rotation={[0, 0, 2.71]} scale={-1}>
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007.geometry}
            material={gltf.materials["Titanium -  Pure"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_1.geometry}
            material={getSolarPanelMaterial(gltf)}
          />
          <T.Mesh
            geometry={gltf.nodes.Solar_Panel007_2.geometry}
            material={gltf.materials["Dark Steel"]}
          />
        </T.Group>
      </Transform>
    </SheetObject>
  {:catch error}
    {@render onError(error)}
  {/await}

  {@html ref}
</T>
